

micronaut:
  application:
    name: mn-mongo
  metrics:
    http:
      path: /metrics
  server:
    port: 8080
    context-path: dave
  security:
    enabled: false
  http:
    client:
      connect-timeout: 1000ms
      read-timeout: 5000ms
      read-idle-timeout: 5m
      pool:
        enabled: true
        acquire-timeout: 1000ms
      channel-options:
        tcp-keepidle: 5
        tcp-keepinterval: 5
        tcp-keepcount: 1
      connect-ttl: 30s
  caches:
    discovery-client:
      enabled: false
      expire-after-access: 5s

endpoints:
  beans:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

readiness:
  initial: true

mongodb:
  #uri: mongodb://mongo1,mongo2,mongo3:27017/example
  uri: mongodb://localhost:27017/admin
  options: connectTimeoutMS=5000&socketTimeoutMS=5000&serverSelectionTimeoutMS=5000&maxPoolSize=15&minPoolSize=5
  db_connection_pool_wait_threshold: 40
  collections:
    - name: orders
      indexes:
        - name: order_id_idx
          unique: true
          ascending: true
          fields:
            - orderId
#      - name: location_id_idx
#        fields:
#          - locationId
#      - name: document_ttl_idx
#        ttl_seconds: 604800 # 7 days
#        fields:
#          - completedTimestamp
