version: "3.7"
services:
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:4.4.2-bionic
    expose:
    - 27017
    ports:
      - 27017:27017
    restart: always

  mongoclient:
    image: mongoclient/mongoclient
    container_name: mongoclient
    ports:
      - "3000:3000"
    environment:
#      MONGO_URL: "mongodb://mongo1,mongo2,mongo3:27017/example?replicaSet=dave"
      MONGOCLIENT_DEFAULT_CONNECTION_URL: "mongodb://mongo1:27017/admin"
      STARTUP_DELAY: "30s"
