version: "3.7"
services:
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:4.4.2-bionic
    expose:
    - 27017
    ports:
      - 30001:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dave" ]
    environment:
      MONGO_INITDB_DATABASE: example
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:4.4.2-bionic
    expose:
    - 27017
    ports:
    - 30002:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dave" ]
    environment:
      MONGO_INITDB_DATABASE: example
  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo:4.4.2-bionic
    expose:
    - 27017
    ports:
    - 30003:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dave" ]
    environment:
      MONGO_INITDB_DATABASE: example
  mongosetup:
    container_name: mongosetup
    image: mongo:4.4.2-bionic
    volumes:
      - ./scripts:/scripts
    entrypoint: ["bash", "/scripts/mongoSetup.sh"]

  mongoclient:
    image: mongoclient/mongoclient
    container_name: mongoclient
    ports:
      - "3000:3000"
    environment:
#      MONGO_URL: "mongodb://mongo1,mongo2,mongo3:27017/example?replicaSet=dave"
      MONGOCLIENT_DEFAULT_CONNECTION_URL: "mongodb://mongo1,mongo2,mongo3:27017/example?replicaSet=dave"
      STARTUP_DELAY: "30s"
